-- Customers
INSERT INTO customers (name, email, city) VALUES ('Alice Smith', 'alice@example.com', 'New York');
INSERT INTO customers (name, email, city) VALUES ('Bob Jones', 'bob@example.com', 'Los Angeles');
INSERT INTO customers (name, email, city) VALUES ('Charlie Brown', 'charlie@example.com', 'Chicago');
INSERT INTO customers (name, email, city) VALUES ('David Wilson', 'david@example.com', 'Houston');
INSERT INTO customers (name, email, city) VALUES ('Eva Davis', 'eva@example.com', 'Phoenix');
INSERT INTO customers (name, email, city) VALUES ('Frank Miller', 'frank@example.com', 'Philadelphia');
INSERT INTO customers (name, email, city) VALUES ('Grace Taylor', 'grace@example.com', 'San Antonio');
INSERT INTO customers (name, email, city) VALUES ('Harry Anderson', 'harry@example.com', 'San Diego');
INSERT INTO customers (name, email, city) VALUES ('Ivy Thomas', 'ivy@example.com', 'Dallas');
INSERT INTO customers (name, email, city) VALUES ('Jack Jackson', 'jack@example.com', 'San Jose');
INSERT INTO customers (name, email, city) VALUES ('Karen White', 'karen@example.com', 'Austin');
INSERT INTO customers (name, email, city) VALUES ('Leo Harris', 'leo@example.com', 'Jacksonville');
INSERT INTO customers (name, email, city) VALUES ('Mia Martin', 'mia@example.com', 'Fort Worth');
INSERT INTO customers (name, email, city) VALUES ('Nathan Thompson', 'nathan@example.com', 'Columbus');
INSERT INTO customers (name, email, city) VALUES ('Olivia Garcia', 'olivia@example.com', 'Charlotte');
INSERT INTO customers (name, email, city) VALUES ('Paul Martinez', 'paul@example.com', 'San Francisco');
INSERT INTO customers (name, email, city) VALUES ('Quinn Robinson', 'quinn@example.com', 'Indianapolis');
INSERT INTO customers (name, email, city) VALUES ('Rachel Clark', 'rachel@example.com', 'Seattle');
INSERT INTO customers (name, email, city) VALUES ('Sam Rodriguez', 'sam@example.com', 'Denver');
INSERT INTO customers (name, email, city) VALUES ('Tina Lewis', 'tina@example.com', 'Washington');

-- Products
INSERT INTO products (name, category, price) VALUES ('Laptop', 'Electronics', 999.99);
INSERT INTO products (name, category, price) VALUES ('Smartphone', 'Electronics', 699.99);
INSERT INTO products (name, category, price) VALUES ('Headphones', 'Accessories', 149.99);
INSERT INTO products (name, category, price) VALUES ('Monitor', 'Electronics', 249.99);
INSERT INTO products (name, category, price) VALUES ('Keyboard', 'Accessories', 89.99);
INSERT INTO products (name, category, price) VALUES ('Mouse', 'Accessories', 49.99);
INSERT INTO products (name, category, price) VALUES ('Desk Chair', 'Furniture', 199.99);
INSERT INTO products (name, category, price) VALUES ('Standing Desk', 'Furniture', 499.99);
INSERT INTO products (name, category, price) VALUES ('Coffee Maker', 'Appliances', 79.99);
INSERT INTO products (name, category, price) VALUES ('Blender', 'Appliances', 59.99);
INSERT INTO products (name, category, price) VALUES ('Toaster', 'Appliances', 39.99);
INSERT INTO products (name, category, price) VALUES ('Microwave', 'Appliances', 129.99);
INSERT INTO products (name, category, price) VALUES ('T-Shirt', 'Clothing', 19.99);
INSERT INTO products (name, category, price) VALUES ('Jeans', 'Clothing', 49.99);
INSERT INTO products (name, category, price) VALUES ('Sneakers', 'Clothing', 89.99);
INSERT INTO products (name, category, price) VALUES ('Jacket', 'Clothing', 119.99);
INSERT INTO products (name, category, price) VALUES ('Backpack', 'Accessories', 59.99);
INSERT INTO products (name, category, price) VALUES ('Watch', 'Accessories', 199.99);
INSERT INTO products (name, category, price) VALUES ('Sunglasses', 'Accessories', 149.99);
INSERT INTO products (name, category, price) VALUES ('Umbrella', 'Accessories', 24.99);

-- Orders
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (1, 1, 1, 999.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (2, 3, 2, 299.98);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (3, 5, 1, 89.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (4, 7, 1, 199.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (5, 9, 1, 79.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (6, 11, 1, 39.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (7, 13, 3, 59.97);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (8, 15, 1, 89.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (9, 17, 1, 59.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (10, 19, 1, 149.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (11, 2, 1, 699.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (12, 4, 2, 499.98);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (13, 6, 1, 49.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (14, 8, 1, 499.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (15, 10, 1, 59.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (16, 12, 1, 129.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (17, 14, 2, 99.98);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (18, 16, 1, 119.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (19, 18, 1, 199.99);
INSERT INTO orders (customer_id, product_id, quantity, total_amount) VALUES (20, 20, 2, 49.98);
